# Generated by Django 5.2.6 on 2025-09-10 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_form'),
    ]

    operations = [
        migrations.RenameField(
            model_name='form',
            old_name='name',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='car',
            name='name',
        ),
        migrations.AddField(
            model_name='car',
            name='username',
            field=models.CharField(default='defaultuser', max_length=100),
            preserve_default=False,
        ),
    ]
