# Generated by Django 5.2.6 on 2025-09-10 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_rename_name_form_username_remove_car_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='form',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
