# Generated by Django 5.2.6 on 2025-09-10 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_alter_form_password_alter_form_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='password',
            field=models.CharField(default=True, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='form',
            name='username',
            field=models.CharField(default='admin', max_length=100),
            preserve_default=False,
        ),
    ]
