# Generated by Django 5.2.6 on 2025-09-08 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['price'], 'verbose_name': 'zaghlol', 'verbose_name_plural': 'zaghlol'},
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('food', 'food'), ('clothes', 'clothes'), ('electronics', 'electronics'), ('books', 'books'), ('other', 'other')], max_length=100, null=True),
        ),
    ]
