# Generated by Django 5.2.6 on 2025-09-08 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_options_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('food', 'food'), ('clothes', 'clothes'), ('electronics', 'electronics'), ('books', 'books'), ('other', 'other')], help_text='select a category for the product', max_length=100, null=True),
        ),
    ]
