# Generated by Django 5.2.6 on 2025-09-08 14:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_test_alter_product_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='date',
        ),
        migrations.RemoveField(
            model_name='product',
            name='datetime',
        ),
        migrations.RemoveField(
            model_name='product',
            name='time',
        ),
        migrations.AlterField(
            model_name='test',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
